export const workflows = [
 {key:'missed_call',name:'Missed-call recovery',description:'Prepare a reply when a caller could not reach you.',label:'Missed call',marketing:false},
 {key:'quote',name:'Quote follow-up',description:'Keep open estimates moving after their follow-up date.',label:'Quote follow-up',marketing:false},
 {key:'invoice',name:'Overdue invoice',description:'Remind customers about invoices past their due date.',label:'Invoice reminder',marketing:false},
 {key:'review',name:'Review request',description:'Ask for honest feedback after a completed job.',label:'Review request',marketing:true},
 {key:'reactivation',name:'Customer reactivation',description:'Reconnect with customers due for another visit.',label:'Reactivation',marketing:true},
] as const;
export const defaultConfig={industry:'Home services',timezone:'America/Los_Angeles',greeting:'Thanks for calling. I can help with a service request or take a message for our team.',services:'Heating repair, air conditioning, maintenance',handoff:'For urgent requests, our team will call you back.',hours:'Monday–Friday, 9 AM–5 PM',rules:Object.fromEntries(workflows.map(w=>[w.key,true]))};
export function followup(kind:string,name:string,business:string,title:string){const first=name.split(' ')[0];const copy:Record<string,string>={missed_call:`Hi ${first}, this is ${business}. Sorry we missed your call. How can we help?`,quote:`Hi ${first}, ${business} here. Do you have any questions about your ${title.toLowerCase()} estimate?`,invoice:`Hi ${first}, a reminder from ${business}: your ${title.toLowerCase()} invoice is past its due date. Please contact our team if you need help.`,review:`Hi ${first}, thank you for choosing ${business}. We'd appreciate your honest feedback on your recent visit.`,reactivation:`Hi ${first}, it's ${business}. Is it time to schedule your next service? Reply if you'd like our team to help.`};return (copy[kind]||'')+' Reply STOP to opt out.';}
export function receptionistReply(input:string,config:typeof defaultConfig){if(/\b(fire|gas leak|smell gas|danger|emergency)\b/i.test(input))return 'If there is immediate danger, contact local emergency services. I cannot provide emergency assistance. I can leave a message for the team.';if(/\b(hours|open|close)\b/i.test(input))return `Our service hours are ${config.hours}.`;if(/\b(price|cost|quote|estimate)\b/i.test(input))return 'Our team will confirm pricing after learning more about the job. Please share the service you need and your preferred callback time.';if(/\b(book|appointment|schedule)\b/i.test(input))return 'I can collect your booking request. What service do you need and which day works for you? Our team will confirm availability.';return `We help with ${config.services.toLowerCase()}. Please describe the issue and your preferred callback time. ${config.handoff}`;}
