/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars, prefer-const */
import { z } from 'zod';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { database } from '@/db/database';
import { env } from 'cloudflare:workers';
import { defaultConfig,workflows,followup,receptionistReply } from '@/lib/domain';
export const dynamic='force-dynamic';
const id=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const text=z.string().trim().min(1).max(200);
const phone=z.string().trim().regex(/^\+[1-9]\d{7,14}$/,'Use an international number such as +14155550101');
const customerInput=z.object({name:text,phone,email:z.union([z.string().email().max(254),z.literal('')]).default(''),notes:z.string().max(3000).default(''),sms_consent:z.boolean().default(false),marketing_consent:z.boolean().default(false)});
class ApiError extends Error {constructor(public status:number,message:string){super(message)}}
const fail=(status:number,message:string):never=>{throw new ApiError(status,message)};
async function user(){const u=await getChatGPTUser();if(!u)fail(401,'Enter the local workspace to continue.');return u!;}
async function own(db:D1Database,w:string,owner:string){const ws=await db.prepare('SELECT * FROM workspaces WHERE id=? AND owner=?').bind(w,owner).first<any>();if(!ws)fail(404,'Workspace not found.');return ws;}
async function customer(db:D1Database,w:string,c:string){const row=await db.prepare('SELECT * FROM customers WHERE id=? AND workspace=?').bind(c,w).first<any>();if(!row)fail(404,'Customer not found.');return row;}
function response(data:any,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
function error(e:unknown){if(e instanceof ApiError)return response({error:e.message},e.status);if(e instanceof z.ZodError)return response({error:e.issues[0]?.message||'Invalid input'},400);if(e instanceof SyntaxError)return response({error:'Invalid request body.'},400);console.error(e);return response({error:'The request could not be saved. Please try again.'},500);}
export async function GET(request:Request){try{const u=await user(),db=database(),w=new URL(request.url).searchParams.get('workspace');const all=await db.prepare('SELECT id,name,created FROM workspaces WHERE owner=? ORDER BY created').bind(u.userId).all();if(!w)return response({workspaces:all.results});const ws=await own(db,w,u.userId);const results=await db.batch(['customers','items','bookings','messages','tasks'].map(t=>db.prepare(`SELECT * FROM ${t} WHERE workspace=? ORDER BY created DESC`).bind(w)));return response({workspaces:all.results,workspace:{...ws,owner:undefined,config:JSON.parse(ws.config)},...Object.fromEntries(['customers','items','bookings','messages','tasks'].map((t,i)=>[t,results[i].results]))});}catch(e){return error(e)}}
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin)fail(403,'Cross-site requests are not allowed.');const u=await user();if(Number(request.headers.get('content-length')||0)>20000)fail(413,'Request too large.');const raw=await request.text();if(raw.length>20000)fail(413,'Request too large.');const body=z.record(z.unknown()).parse(JSON.parse(raw)),action=z.string().parse(body.action),db=database();
if(action==='create_workspace'){const name=text.parse(body.name);const count=await db.prepare('SELECT count(*) AS n FROM workspaces WHERE owner=?').bind(u.userId).first<{n:number}>();if((count?.n||0)>=10)fail(400,'The local demo supports up to 10 workspaces.');const w=id();await db.prepare('INSERT INTO workspaces(id,owner,name,config,created) VALUES(?,?,?,?,?)').bind(w,u.userId,name,JSON.stringify(defaultConfig),now()).run();if(body.sample===true)await seed(db,w,name);return response({id:w},201);}
const w=z.string().uuid().parse(body.workspace),ws=await own(db,w,u.userId),config=JSON.parse(ws.config);
if(action==='create_customer'){const c=customerInput.parse(body);const cid=id();try{await db.prepare('INSERT INTO customers(id,workspace,name,phone,email,notes,sms_consent,marketing_consent,created) VALUES(?,?,?,?,?,?,?,?,?)').bind(cid,w,c.name,c.phone,c.email,c.notes,+c.sms_consent,+c.marketing_consent,now()).run()}catch(e){if(String(e).includes('UNIQUE'))fail(409,'A customer with that phone number already exists.');throw e}return response({id:cid},201);}
if(action==='update_customer'){const c=await customer(db,w,z.string().parse(body.id));const input=z.object({stage:z.enum(['New lead','Contacted','Booked','Customer','Inactive']),notes:z.string().max(3000),sms_consent:z.boolean(),marketing_consent:z.boolean(),opted_out:z.boolean()}).parse(body);await db.prepare('UPDATE customers SET stage=?,notes=?,sms_consent=?,marketing_consent=?,opted_out=? WHERE id=? AND workspace=?').bind(input.stage,input.notes,+input.sms_consent,+input.marketing_consent,+input.opted_out,c.id,w).run();return response({ok:true});}
if(action==='create_item'){const v=z.object({customer:z.string(),kind:z.enum(['missed_call','quote','invoice','review','reactivation']),title:text,amount:z.number().int().min(0).max(100000000),due:z.string().datetime()}).parse(body);await customer(db,w,v.customer);const iid=id();await db.prepare('INSERT INTO items(id,workspace,customer,kind,title,amount,due,created) VALUES(?,?,?,?,?,?,?,?)').bind(iid,w,v.customer,v.kind,v.title,v.amount,v.due,now()).run();return response({id:iid},201);}
if(action==='close_item'){const iid=z.string().parse(body.id);const result=await db.prepare("UPDATE items SET status='closed' WHERE id=? AND workspace=?").bind(iid,w).run();if(!result.meta.changes)fail(404,'Opportunity not found.');await db.prepare("UPDATE tasks SET status='dismissed' WHERE source=? AND workspace=? AND status='draft'").bind(iid,w).run();return response({ok:true});}
if(action==='book'){
 const v=z.object({customer:z.string(),title:text,start:z.string().refine(v=>!Number.isNaN(Date.parse(v)),'Invalid datetime'),source:z.string().optional()}).parse(body);
 await customer(db,w,v.customer);
 const dt=new Date(v.start);
 if(dt.getTime()<=Date.now()||dt.getUTCMinutes()!==0||dt.getUTCSeconds()!==0||dt.getUTCMilliseconds()!==0)fail(400,'Choose a future appointment on the hour.');
 if(v.source){const item=await db.prepare("SELECT id FROM items WHERE id=? AND workspace=? AND customer=? AND status='open' AND kind IN ('missed_call','quote','reactivation')").bind(v.source,w,v.customer).first();if(!item)fail(409,'Choose an open booking opportunity belonging to this customer.');}
 const bid=id();const statements=[db.prepare('INSERT INTO bookings(id,workspace,customer,source,title,start,created) VALUES(?,?,?,?,?,?,?)').bind(bid,w,v.customer,v.source||null,v.title,dt.toISOString(),now()),db.prepare("UPDATE customers SET stage='Booked' WHERE id=? AND workspace=?").bind(v.customer,w)];
 if(v.source)statements.push(db.prepare("UPDATE items SET status='booked' WHERE id=? AND workspace=?").bind(v.source,w),db.prepare("UPDATE tasks SET status='dismissed' WHERE source=? AND workspace=? AND status='draft'").bind(v.source,w));
 try{await db.batch(statements)}catch(e){if(String(e).includes('UNIQUE'))fail(409,'This hour or opportunity is already booked. Choose another time or refresh the workspace.');throw e}
 return response({id:bid},201);
}
if(action==='cancel_booking'){
 const bid=z.string().parse(body.id);
 const booking=await db.prepare('SELECT * FROM bookings WHERE id=? AND workspace=?').bind(bid,w).first<any>();if(!booking)fail(404,'Booking not found.');if(booking.status==='canceled')fail(409,'This appointment is already canceled.');
 const statements=[db.prepare("UPDATE bookings SET status='canceled' WHERE id=? AND workspace=? AND status='confirmed'").bind(bid,w),db.prepare("UPDATE customers SET stage='Contacted' WHERE id=? AND workspace=? AND stage='Booked' AND NOT EXISTS(SELECT 1 FROM bookings WHERE customer=? AND workspace=? AND status='confirmed' AND start>?)").bind(booking.customer,w,booking.customer,w,now())];
 if(booking.source)statements.push(db.prepare("UPDATE items SET status='open' WHERE id=? AND workspace=? AND status='booked'").bind(booking.source,w));
 await db.batch(statements);return response({ok:true});
}
if(action==='save_config'){const v=z.object({industry:text,timezone:z.string().refine(v=>{try{new Intl.DateTimeFormat('en',{timeZone:v});return true}catch{return false}},'Invalid time zone'),businessPhone:z.string().trim().max(30),greeting:z.string().min(1).max(1000),services:text,handoff:z.string().min(1).max(500),hours:text,rules:z.object({missed_call:z.boolean(),quote:z.boolean(),invoice:z.boolean(),review:z.boolean(),reactivation:z.boolean()})}).parse(body.config);await db.prepare('UPDATE workspaces SET config=? WHERE id=? AND owner=?').bind(JSON.stringify(v),w,u.userId).run();return response({ok:true});}
if(action==='simulate_call'){const cid=z.string().parse(body.customer),c=await customer(db,w,cid);const message=z.string().trim().min(1).max(1000).parse(body.message);const missed=body.missed===true;const reply=missed?'Missed call recorded. Run Autopilot to prepare a follow-up.':receptionistReply(message,config);const statements=[db.prepare('INSERT INTO messages(id,workspace,customer,body,direction,status,created) VALUES(?,?,?,?,?,?,?)').bind(id(),w,cid,message,'inbound','simulated',now())];if(missed)statements.push(db.prepare('INSERT INTO items(id,workspace,customer,kind,title,amount,due,created) VALUES(?,?,?,?,?,?,?,?)').bind(id(),w,cid,'missed_call','Missed call',0,now(),now()));else statements.push(db.prepare('INSERT INTO messages(id,workspace,customer,body,direction,status,created) VALUES(?,?,?,?,?,?,?)').bind(id(),w,cid,reply,'outbound','simulated',now()));await db.batch(statements);return response({reply,customer:c.name});}
if(action==='intake_call'){
 const v=z.object({name:text,phone,email:z.union([z.string().email().max(254),z.literal('')]).default(''),service:text,preferredStart:z.string().refine(v=>!Number.isNaN(Date.parse(v)),'Invalid datetime').optional(),smsConsent:z.boolean().default(false)}).parse(body);
 let c=await db.prepare('SELECT * FROM customers WHERE workspace=? AND phone=?').bind(w,v.phone).first<any>();
 let cid=c?.id||id(); const created=!c;
 if(created){await db.prepare('INSERT INTO customers(id,workspace,name,phone,email,stage,sms_consent,marketing_consent,notes,created) VALUES(?,?,?,?,?,?,?,0,?,?)').bind(cid,w,v.name,v.phone,v.email,'New lead',+v.smsConsent,`Call intake: ${v.service}`,now()).run();c={id:cid,name:v.name,phone:v.phone};}
 const itemId=id(), stamp=now();
 const statements=[db.prepare('INSERT INTO messages(id,workspace,customer,body,direction,status,created) VALUES(?,?,?,?,?,?,?)').bind(id(),w,cid,`Call request: ${v.service}`,'inbound','simulated',stamp),db.prepare('INSERT INTO items(id,workspace,customer,kind,title,amount,due,created) VALUES(?,?,?,?,?,?,?,?)').bind(itemId,w,cid,'missed_call',v.service,0,stamp,stamp),db.prepare('INSERT INTO messages(id,workspace,customer,body,direction,status,created) VALUES(?,?,?,?,?,?,?)').bind(id(),w,cid,`Thanks, ${v.name.split(' ')[0]}. I have your ${v.service.toLowerCase()} request. We will confirm the appointment details shortly.`,'outbound','simulated',stamp)];
 if(v.preferredStart){const dt=new Date(v.preferredStart);if(dt<=new Date()||dt.getUTCMinutes()!==0)fail(400,'Choose a future appointment on the hour.');statements.push(db.prepare('INSERT INTO bookings(id,workspace,customer,source,title,start,created) VALUES(?,?,?,?,?,?,?)').bind(id(),w,cid,itemId,`${v.service} visit`,dt.toISOString(),stamp),db.prepare("UPDATE items SET status='booked' WHERE id=? AND workspace=?").bind(itemId,w),db.prepare("UPDATE customers SET stage='Booked' WHERE id=? AND workspace=?").bind(cid,w));}
 await db.batch(statements);return response({customer:cid,created,booked:Boolean(v.preferredStart),confirmation:`${v.service} request captured for ${c.name}.`},201);
}
if(action==='simulate_sms'){const cid=z.string().parse(body.customer),c=await customer(db,w,cid),message=z.string().trim().min(1).max(1600).parse(body.message);const inbound=body.inbound===true;if(!inbound&&(!c.sms_consent||c.opted_out))fail(409,'This customer is not eligible for text messages.');const stmts=[db.prepare('INSERT INTO messages(id,workspace,customer,body,direction,status,created) VALUES(?,?,?,?,?,?,?)').bind(id(),w,cid,message,inbound?'inbound':'outbound','simulated',now())];if(inbound&&/^(stop|unsubscribe|cancel|end|quit)$/i.test(message))stmts.push(db.prepare('UPDATE customers SET opted_out=1,sms_consent=0,marketing_consent=0 WHERE id=? AND workspace=?').bind(cid,w));await db.batch(stmts);return response({ok:true});}
if(action==='run_autopilot'){const rows=await db.prepare("SELECT i.*,c.name,c.sms_consent,c.marketing_consent,c.opted_out FROM items i JOIN customers c ON c.id=i.customer AND c.workspace=i.workspace WHERE i.workspace=? AND i.status='open' AND i.due<=?").bind(w,now()).all<any>();let generated=0,skipped=0;for(const item of rows.results){const rule=workflows.find(r=>r.key===item.kind);if(!rule||!config.rules[rule.key]||!item.sms_consent||item.opted_out||(rule.marketing&&!item.marketing_consent)){skipped++;continue}const result=await db.prepare("INSERT OR IGNORE INTO tasks(id,workspace,customer,source,kind,body,status,created) VALUES(?,?,?,?,?,?,'draft',?)").bind(id(),w,item.customer,item.id,item.kind,followup(item.kind,item.name,ws.name,item.title),now()).run();generated+=result.meta.changes;}return response({generated,skipped});}
if(action==='review_task'){const t=await db.prepare('SELECT * FROM tasks WHERE id=? AND workspace=?').bind(z.string().parse(body.id),w).first<any>();if(!t)fail(404,'Follow-up not found.');if(t.status!=='draft')fail(409,'This follow-up has already been reviewed.');if(body.dismiss===true){await db.prepare("UPDATE tasks SET status='dismissed' WHERE id=? AND workspace=? AND status='draft'").bind(t.id,w).run();return response({ok:true})}const c=await customer(db,w,t.customer);const rule=workflows.find(r=>r.key===t.kind);const source=await db.prepare("SELECT id FROM items WHERE id=? AND workspace=? AND status='open'").bind(t.source,w).first();if(!source||!rule||!config.rules[rule.key]||!c.sms_consent||c.opted_out||(rule.marketing&&!c.marketing_consent))fail(409,'This follow-up is no longer eligible. Check the source, workflow, and customer permissions.');const message=z.string().trim().min(1).max(1600).parse(body.message);await db.batch([db.prepare("INSERT OR IGNORE INTO messages(id,workspace,customer,body,direction,status,created) SELECT ?,?,?,?,'outbound','simulated',? WHERE EXISTS(SELECT 1 FROM tasks WHERE id=? AND workspace=? AND status='draft')").bind(t.id,w,t.customer,message,now(),t.id,w),db.prepare("UPDATE tasks SET status='simulated',body=? WHERE id=? AND workspace=? AND status='draft'").bind(message,t.id,w)]);return response({ok:true});}
if(action==='call_me'){
 const to=phone.parse(body.phone); const sid=String((env as any).TWILIO_ACCOUNT_SID||''); const token=String((env as any).TWILIO_AUTH_TOKEN||''); const from=String((env as any).TWILIO_PHONE_NUMBER||config.businessPhone||''); const base=String((env as any).PUBLIC_BASE_URL||'');
 if(!sid||!token||!from||!base)fail(503,'Telephony is not configured. Add Twilio credentials, TWILIO_PHONE_NUMBER, and PUBLIC_BASE_URL.');
 const form=new URLSearchParams({To:to,From:from,Url:`${base.replace(/\/$/,'')}/api/voice`}); const result=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Calls.json`,{method:'POST',headers:{Authorization:`Basic ${btoa(`${sid}:${token}`)}`,'Content-Type':'application/x-www-form-urlencoded'},body:form}); const json:any=await result.json(); if(!result.ok)fail(502,json.message||'Twilio could not start the call.'); return response({ok:true,callSid:json.sid});
}
fail(400,'Unknown action.');
}catch(e){return error(e)}}
async function seed(db:D1Database,w:string,business:string){const data=[['Maya Chen','+14155550101','New lead','Furnace not heating. Prefers afternoon callbacks.'],['James Wilson','+14155550102','Contacted','Considering a replacement system.'],['Alex Patel','+14155550103','Customer','Annual maintenance customer.'],['Sofia Rivera','+14155550104','Inactive','Last visit was six months ago.'],['Oliver Brooks','+14155550105','Customer','Recent tune-up completed.'],['Emma Davis','+14155550106','Booked','Requested an AC inspection.']];const ids=data.map(()=>id());const stmts=data.map((c,i)=>db.prepare('INSERT INTO customers(id,workspace,name,phone,email,stage,sms_consent,marketing_consent,notes,created) VALUES(?,?,?,?,?,?,1,1,?,?)').bind(ids[i],w,c[0],c[1],c[0].toLowerCase().split(' ')[0]+'@example.com',c[2],c[3],now()));const due=new Date(Date.now()-86400000).toISOString();const values=[[0,'missed_call','Heating repair',35000],[1,'quote','System replacement',620000],[2,'invoice','Annual maintenance',28000],[3,'reactivation','Seasonal service',22000],[4,'review','Completed tune-up',0]];for(const [i,kind,title,amount] of values)stmts.push(db.prepare('INSERT INTO items(id,workspace,customer,kind,title,amount,due,created) VALUES(?,?,?,?,?,?,?,?)').bind(id(),w,ids[Number(i)],kind,title,amount,due,now()));for(let i=0;i<3;i++){const start=new Date();start.setDate(start.getDate()+i+1);start.setHours(10+i,0,0,0);stmts.push(db.prepare('INSERT INTO bookings(id,workspace,customer,title,start,created) VALUES(?,?,?,?,?,?)').bind(id(),w,ids[5-i],['AC inspection','Post-service check-in','Seasonal maintenance'][i],start.toISOString(),now()))}stmts.push(db.prepare('INSERT INTO messages(id,workspace,customer,body,direction,status,created) VALUES(?,?,?,?,?,?,?)').bind(id(),w,ids[0],'Hi, our furnace stopped heating. Do you have any availability this week?','inbound','simulated',now()));await db.batch(stmts);}
